/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2024-09-11 07:44:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class StudentForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"StudentSevlet\" method = \"post\">\r\n");
      out.write("	\r\n");
      out.write("	    <label>First name</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtFirstName\" maxlength=\"30\" placeholder=\"(max 30 characters a-z and A-z)\"> <br><br>\r\n");
      out.write("	    <label>Last name</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtLastName\" maxlength=\"30\" placeholder=\"(max 30 characters a-z and A-z)\"><br><br>\r\n");
      out.write("	    <label>Date of birth</label> \r\n");
      out.write("	    <select id=\"ngay\" name=\"day\">\r\n");
      out.write("            <option value=\"01\">1</option>\r\n");
      out.write("            <option value=\"02\">2</option>\r\n");
      out.write("            <option value=\"03\">3</option>\r\n");
      out.write("            <option value=\"04\">4</option>\r\n");
      out.write("            <option value=\"05\">5</option>\r\n");
      out.write("            <option value=\"06\">6</option>\r\n");
      out.write("            <option value=\"07\">7</option>\r\n");
      out.write("            <option value=\"08\">8</option>\r\n");
      out.write("            <option value=\"09\">9</option>\r\n");
      out.write("            <option value=\"10\">10</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <select id=\"thang\" name=\"month\">\r\n");
      out.write("            <option value=\"01\">1</option>\r\n");
      out.write("            <option value=\"02\">2</option>\r\n");
      out.write("            <option value=\"03\">3</option>\r\n");
      out.write("            <option value=\"04\">4</option>\r\n");
      out.write("            <option value=\"05\">5</option>\r\n");
      out.write("            <option value=\"06\">6</option>\r\n");
      out.write("            <option value=\"07\">7</option>\r\n");
      out.write("            <option value=\"08\">8</option>\r\n");
      out.write("            <option value=\"09\">9</option>\r\n");
      out.write("            <option value=\"10\">10</option>\r\n");
      out.write("            <option value=\"11\">11</option>\r\n");
      out.write("            <option value=\"12\">12</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <select id=\"name\" name=\"year\">\r\n");
      out.write("            <option value=\"2003\">2003</option>\r\n");
      out.write("            <option value=\"2004\">2004</option>\r\n");
      out.write("            <option value=\"2005\">2005</option>\r\n");
      out.write("            <option value=\"2006\">2006</option>\r\n");
      out.write("        </select><br><br>\r\n");
      out.write("	    <label>Email</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtEmail\" maxlength=\"30\"><br><br>\r\n");
      out.write("	    <label>Mobile number</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtPhone\" maxlength=\"30\" placeholder=\"(10 digit number)\"><br><br>\r\n");
      out.write("	    <label>Gender</label> \r\n");
      out.write("	    <label><input type=\"radio\" name=\"gioitinh\" value=\"nam\" required>Nam</label>\r\n");
      out.write("	    <label><input type=\"radio\" name=\"gioitinh\" value=\"nu\">Nu</label><br><br>\r\n");
      out.write("	    <label>Address</label> \r\n");
      out.write("	    <textarea rows=\"4\" cols=\"10\" name=\"txtAddress\"></textarea><br><br>\r\n");
      out.write("	    <label>City</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtCity\" maxlength=\"30\" placeholder=\"(max 30 characters a-z and A-z)\"><br><br>\r\n");
      out.write("	    <label>Pin code</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtPincode\" maxlength=\"30\" placeholder=\"(6 dgit number)\"><br><br>\r\n");
      out.write("	    <label>State</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtState\" maxlength=\"30\" placeholder=\"(max 30 characters a-z and A-z)\"><br><br>\r\n");
      out.write("	    <label>Country</label> \r\n");
      out.write("	    <input type=\"text\" name=\"txtCountry\" maxlength=\"30\"><br><br>\r\n");
      out.write("	    <label>Hobibies</label> \r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"hobbies\" value=\"Drawing\">Drawing</label>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"hobbies\" value=\"Singing\">Singing</label>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"hobbies\" value=\"Dancing\">Dancing</label>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"hobbies\" value=\"Sketching\">Sketching</label><br><br>\r\n");
      out.write("	    <!-- Thieu table va other hobbies -->\r\n");
      out.write("	    <label>Course applies for</label> \r\n");
      out.write("	    <label><input type=\"radio\" name=\"course\" value=\"BCA\" required>BCA</label>\r\n");
      out.write("	    <label><input type=\"radio\" name=\"course\" value=\"Com\">Com</label>\r\n");
      out.write("	    <label><input type=\"radio\" name=\"course\" value=\"B.SC\" required>B.SC</label>\r\n");
      out.write("	    <label><input type=\"radio\" name=\"course\" value=\"B.A\">B.A</label><br><br>\r\n");
      out.write("	    \r\n");
      out.write("	    <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("	    <input type=\"reset\" value=\"Reset\">\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
